image: java:8-jdk

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +xX gradlew

build:
  stage: build
  script:
    - ./gradlew genSources
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - master

after_script:
  - echo "End CI"